version: '3.7'

services:
  app:
    hostname: tinyapp
    image: shopware/development:8.1-composer-2
    volumes:
      - ./:/app/
    ports:
      - 80:80
    networks:
      - app_net

  mysql:
    image: mysql:8
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: apptemplate
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root

  wait-for-it:
    image: blablalines/wait:2.6.0-slim

networks:
  app_net:
    external:
      name: app_net