name: Test registration process
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-registration-process:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: 'docker-compose up -d'

      - name: Install dependencies
        run: 'docker-compose exec -T app composer install --no-interaction'

      - name: Wait for MySQL server
        run: 'docker-compose run -e WAIT_HOSTS=mysql:3306 wait-for-it'

      - name: Run migrations
        run: 'docker-compose exec -T app php bin/console doctrine:migrations:migrate'
